packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@swc/core': true
  cpu-features: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  ssh2: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@swc/core"
  - cpu-features
  - esbuild
  - msgpackr-extract
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
