-- Generated by drizzle-kit generate (CLAUDE.md §2.1) from
-- packages/db/src/schema/rollup.ts — TASK-home-dashboard §2.1. RLS for these
-- three tables and the third SECURITY DEFINER function follow in 0010, same
-- split as 0004/0005.
CREATE TYPE "public"."weather_horizon" AS ENUM('0', '1', '2', '3', '4', '5', '6', '7');--> statement-breakpoint
CREATE TABLE "farm_daily_rollups" (
	"organization_id" uuid NOT NULL,
	"farm_id" uuid NOT NULL,
	"day" date NOT NULL,
	"payload" jsonb NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "farm_daily_rollups_farm_id_day_pk" PRIMARY KEY("farm_id","day")
);
--> statement-breakpoint
CREATE TABLE "farm_scores" (
	"organization_id" uuid NOT NULL,
	"farm_id" uuid NOT NULL,
	"computed_on" date NOT NULL,
	"score" numeric NOT NULL,
	"class" text NOT NULL,
	"components" jsonb NOT NULL,
	"formula_version" text NOT NULL,
	CONSTRAINT "farm_scores_farm_id_computed_on_pk" PRIMARY KEY("farm_id","computed_on")
);
--> statement-breakpoint
CREATE TABLE "weather_snapshots" (
	"organization_id" uuid NOT NULL,
	"farm_id" uuid NOT NULL,
	"observed_at" timestamp with time zone NOT NULL,
	"horizon" "weather_horizon" NOT NULL,
	"payload" jsonb NOT NULL,
	CONSTRAINT "weather_snapshots_farm_id_observed_at_horizon_pk" PRIMARY KEY("farm_id","observed_at","horizon")
);
--> statement-breakpoint
ALTER TABLE "farm_daily_rollups" ADD CONSTRAINT "farm_daily_rollups_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "farm_daily_rollups" ADD CONSTRAINT "farm_daily_rollups_farm_fk" FOREIGN KEY ("organization_id","farm_id") REFERENCES "public"."farms"("organization_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "farm_scores" ADD CONSTRAINT "farm_scores_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "farm_scores" ADD CONSTRAINT "farm_scores_farm_fk" FOREIGN KEY ("organization_id","farm_id") REFERENCES "public"."farms"("organization_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "weather_snapshots" ADD CONSTRAINT "weather_snapshots_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "weather_snapshots" ADD CONSTRAINT "weather_snapshots_farm_fk" FOREIGN KEY ("organization_id","farm_id") REFERENCES "public"."farms"("organization_id","id") ON DELETE cascade ON UPDATE no action;